<a href="https://colab.research.google.com/github/suvasish114/ML-Notes/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.



In [1]:
%pip install numpy
%pip install matplotlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
# imports
import numpy as np
import matplotlib.pyplot as plt

In [3]:
arr = np.array([1,2,3])         # create an n-dimentional array object
print(arr.dtype)                # document type
print(arr.ndim)                 # number of axes
print(arr.data)                 # the buffer containing the actual elements of the array
print(arr.shape)                # the dimensions of the array
print(arr.size)                 # total number of elements of the array
print(arr.itemsize)             # the size in bytes of each element of the array

int64
1
(3,)
3
8


In [4]:
# showing taken time by a single line
%timeit np.array([1,2,3])

818 ns ± 66.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
# creating multidimentional array
arr = np.array([1,2,3], ndmin = 2)  # creating 2D array
print(arr)                          # printing the array contents
print(arr.ndim)                     # printing dimention of the array

[[1 2 3]]
2


In [6]:
# fill array contents
arr_zeros = np.zeros((3,4))         # create array filled with 0's
arr_ones = np.ones((3,4))           # create array filled with 1's
arr_empty = np.empty((3,4))         # create array filled with empty memory elements (garbages) 

In [7]:
# create sequences of numbers
arr = np.arange(0,10,3)             # 0 to 10 with gap 3
print(arr)

[0 3 6 9]


In [19]:
# RESHAPE THE ARRAY
arr = np.array(range(0,12)).reshape(4,3)
print(arr)
print(f"Ravel: {arr.ravel()}")    # return the whole matrix in 1d array
print(f"Transpose:\n{arr.T}")      # transpose of the array

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Ravel: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [24]:
# MERGING MATRICES
arr1 = np.arange(0,12).reshape(3,4)
arr2 = np.arange(12,16).reshape(1,4)
np.vstack((arr1, arr2))                 # vertically merge

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])