Numpy

In [10]:
import numpy as np
arr = np.array([1,2,3])
print(type(arr))                # printing type of a numpy array
print(arr.ndim)                 # print dimention of the array

<class 'numpy.ndarray'>
1


In [9]:
# showing taken time by a single line
%timeit np.array([1,2,3])

978 ns ± 318 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
# creating multidimentional array
arr = np.array([1,2,3], ndmin = 2)  # creating 2D array
print(arr)                          # printing the array contents
print(arr.ndim)                     # printing dimention of the array

[[1 2 3]]
2


In [12]:
# fill array contents with 0
arr = np.zeros((3,4))               # creating and filling conetnts with 0's
print(arr)                          # printing the array contents
print(arr.ndim)                     # printing dimention of the array

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


In [14]:
# creating an empty array
# the array contents will fill with previously stored memory values
arr = np.empty(4)                   # dimention as arguments
print(arr)                          # printing the array contents
print(arr.ndim)                     # printing dimention of the array

[5.e-324 5.e-324 5.e-324 0.e+000]
1
